### ISSUE TITLE
Filenames for sensor-files are not correct

### ISSUE THREAD

**Issue by stefanwz** [MrIceman11/e3dc-homeassistant#1]
Hi,
the configuration.yaml entries for the sensor-yaml files are:
sensors.yaml and binary_sensors.yaml

But the filenames in the package folder are currently:
sensor.yaml and binary_sensor.yaml

...i'd like to buy an "s" ;-)

**Comment by MrIceman11** [comment]
Hi!

Thank you, have bought two ;-)
