### ISSUE TITLE
`retry_on_empty`: is deprecated and will be removed in version 2024.4

### ISSUE THREAD

**Issue by soloPFL** [MrIceman11/e3dc-homeassistant#11]
When upgrading HA today I got a warning: `retry_on_empty`: is deprecated and will be removed in version 2024.4

Would the solution be just to remove the `retry_on_empty` line from modbus.yaml? Or will this brake the configuration?

great work btw. I hope you are still active.

**Comment by MrIceman11** [comment]
Hi soloPFL,

I'm a bit stumped right now. Normally you can just delete it. Should have no effect. 

Maybe you can give me feedback so I can update the config. I delete it with my Config also times out and test times.

Thanks for the report
