### ISSUE TITLE
SGReady status is missing

### ISSUE THREAD

**Issue by Alpenjohn** [MrIceman11/e3dc-homeassistant#15]
May you please add the SGReady Status?
It is behind the ID 40137
Lenght = 1
Datatype = UInt16

2 = Normal Operation
3 = Solar system is in the overproduction mode.

This is required to start actions based on that, like activate additional power consumers, like the dryer or just use it in combination with a heatpump, like opening all the valves in the house.

**Comment by MrIceman11** [comment]
Thank you!  @SiRMfG 

I will close the Issue then.
