### ISSUE TITLE
invalid config for modbus

### ISSUE THREAD

**Issue by CeeJay-007** [MrIceman11/e3dc-homeassistant#17]
E3DC worked perfectly for more than 2 years, but now:

Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'baudrate' not provided
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'bytesize' not provided
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'method' not provided
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'parity' not provided
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'stopbits' not provided
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 4: not a valid value for dictionary value 'modbus->0->type', got 'tcp'
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 5: 'host' is an invalid option for 'modbus', check: modbus->0->host
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 7: 'retry_on_empty' is an invalid option for 'modbus', check: modbus->0->retry_on_empty

**Comment by clfberlin** [comment]
Ok, strange. I have E3DC up and running without a problem. However, I have my modbus.yaml in a different folder.
Your modbus.yaml file is referenced in your configuration.yaml? The IP-Adress for your inverter is still correct? Modbus is still activated in your inverter? Note that E3DC updated systems recently.

**Comment by CeeJay-007** [comment]
yaml-reference is ok - check
Ip-Adress did not change - check
Modbus ist active - check
modbus TCP is active - check
Hassio restart - check
E3DC restart - check

2024-04-10 16:35:27.832 ERROR (MainThread) [homeassistant.config] Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'baudrate' not provided, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'bytesize' not provided, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'method' not provided, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'parity' not provided, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 3: required key 'stopbits' not provided, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 4: not a valid value for dictionary value 'modbus->0->type', got 'tcp', please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 5: 'host' is an invalid option for 'modbus', check: modbus->0->host, please check the docs at https://www.home-assistant.io/integrations/modbus
Invalid config for 'modbus' at packages/e3dc/modbus.yaml, line 7: 'retry_on_empty' is an invalid option for 'modbus', check: modbus->0->retry_on_empty, please check the docs at https://www.home-assistant.io/integrations/modbus
2024-04-10 16:35:27.833 ERROR (MainThread) [homeassistant.setup] Setup failed for 'modbus': Invalid config.

**Comment by clfberlin** [comment]
Sorry, I am just a user myself and can only try to help by comparing my installation... But the fact that it is looking for 'baudrate' seems odd. Is "type: tcp" in your settings? Or serial?
https://www.home-assistant.io/integrations/modbus

**Comment by CeeJay-007** [comment]
No problems, I'm just wondering about my errors, because nothing changed by myself.
These are the first lines in my "modbus.yaml"

e3dc_modbus:
  modbus:
    - name: "e3dc"
      type: tcp
      host: ***.***.***.***
      port: 502
      retry_on_empty: true

**Comment by clfberlin** [comment]
Ok, "retry_on_empty" is one thing I do not have. Other than that I don't see major differences. The odd thing is that the errors complain about missing data that seem to be relevat only if you are running "type: serial".
For a structured approach: Let's narrow down the possible sources. 
E3DC makes occasional updates. But you confirmed settings in the E3DC itself (and it is set to E3DC mode rather than "Simple Mode"?). And you restarted. 
The YAML files themselves remained untouched and worked until now. I can confirm that they are working here.
So a likely cause is the HA-installation itself.
Here is a similar case from a few years ago:
https://community.home-assistant.io/t/modbus-tcp-invalid-configuration-new-yaml-formatting-extra-keys-key-not-provided-errors/345613
There have been some recent updates. Any chance you can create a backup, then restore an older backup (from maybe a week ago) and compare?

**Comment by CeeJay-007** [comment]
This was my solution:
#      retry_on_empty: true
Thank you clfberlin for the hint!
