### ISSUE TITLE
How to configure password?

### ISSUE THREAD

**Issue by allbutsafe** [MrIceman11/e3dc-homeassistant#7]
Hi,
I've followed the configuration, but "connection refused" appears, because the password is missing.

How do I configure the password set in the E3DC (S 10 X) within the modbus.yaml? Or do I have to remove the password on the E3DC (set to empty) - wouldn't be my preference?

Thanks,
Nils

**Comment by MrIceman11** [comment]
Hi,

Have you activated Modbus in your S10X? 
You have to go to Main Menu > Functions > Function Modbus. The protocol requires E3DC.

Best regards
Julian

**Comment by allbutsafe** [comment]
And this issue can be closed, of course.
